const styles = {
    bg:{
        position: 'relative',
    },
    container:{
        position:'absolute', 
        flex:1,
        width:'100%',
        height:'100%',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'center'   
    },
    content:{
        flex:1,
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'center'   
    },
    image:{
       height:70,
       width:70,
    },
    textView:{
        color:"white",
        fontSize:25,
        fontFamily:"arlrdbd.ttf"
    },
    viewOpacity:{
        position:'absolute',
        justifyContent:'center',
        flex:1,
        flexDirection:'column',
        width:'100%',
    },
    image_01:{
        height:30,
        width:30,
        marginLeft:15
    },
    view_02:{
        margin:10,
        flex:1,
        flexDirection:'row',
        borderBottomWidth:1,
        borderBottomColor:'white',
        marginHorizontal:20
    },
    text_usernam:{
       color: 'white',
       fontSize:20,
       marginHorizontal:20
    },
    image_02:{
        height:35,
        width:35,
    },
    view_03:{
        alignItems:'center',
        justifyContent:'center'   
    },
    button:{
        height:50,
        width:150,
        backgroundColor:'white',
        alignItems:'center',
        justifyContent:'center'   
    }
}
export default styles
